name: CI/CD Pipeline for SimpleCalculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push the Docker Image
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --push -t ${{ secrets.DOCKER_USERNAME }}/simple-calculator:latest .

      # Step 4: Pull and Run the Docker Container
      - name: Deploy Docker Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/simple-calculator:latest
          docker stop simple-calculator || true
          docker rm simple-calculator || true
          docker run -d --name simple-calculator -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/simple-calculator:latest
