name: Test GitHub Secrets

on:
  workflow_dispatch: # Allows manual workflow triggering for testing

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Print DOCKER_USERNAME Secret
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"

      - name: Print DOCKER_PASSWORD Secret (Masked Output)
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "DOCKER_PASSWORD is set"
